### ISSUE TITLE
Incorrect return values for verify_user_password

### ISSUE THREAD

**Issue by abeverley** [Humanstate/net-oauth2-authorizationserver#15]
Unless I am mistaken, the return values specified in the synopsis of Net::OAuth2::AuthorizationServer::PasswordGrant are wrong for verify_user_password.

They are listed as  $is_valid,$error,$scopes, but from the code it looks like they are $client_id, $error, $scopes, $username.

Thanks!

**Comment by leejo** [comment]
Thanks! I've got a few other issues to look at so will get this out along with the fixes to those in the next few weeks.
