### ISSUE TITLE
Returns in try { } catch { } blocks

### ISSUE THREAD

**Issue by dylanwh** [Humanstate/net-oauth2-authorizationserver#20]
I don't believe the [the return on line 260 of  AuthorizationCodeGrant.pm](https://metacpan.org/source/LEEJO/Net-OAuth2-AuthorizationServer-0.18/lib/Net/OAuth2/AuthorizationServer/AuthorizationCodeGrant.pm#L260) will do what the author intended.

I'm also worried there are other places where this happens. I'll audit the code and report my findings here.

**Comment by leejo** [comment]
Resolved by #21
