### ISSUE TITLE
oauth2_client.pl example does not work

### ISSUE THREAD

**Issue by yoe** [Humanstate/net-oauth2-authorizationserver#23]
In one terminal, I run:

    morbo -l "https://*:3000" oauth2_server_realistic.pl daemon

Then, while that is running, I do:

    morbo -l "https://*:3001" oauth2_client.pl

which produces the following output:

    Server available at https://127.0.0.1:3001
    Can't load application from file "/home/wouter/net-oauth2-authorizationserver/examples/oauth2_client.pl": Can't use string ("1") as a HASH ref while "strict refs" in use at /usr/local/share/perl/5.28.1/Mojolicious/Plugin/OAuth2.pm line 45.
    Compilation failed in require at (eval 94) line 1.

**Comment by leejo** [comment]
Hey, thanks for the report. This was an upstream change. I've tweaked the example to fix it but haven't done a release yet (will do so at a later stage)

**Comment by leejo** [comment]
Reopening because the client still contains a `delay` call, which was removed from Mojo in v7.78. See https://github.com/Humanstate/mojolicious-plugin-oauth2-server/issues/23 for context.

**Comment by leejo** [comment]
Fixed. v0.23 on its way to CPAN.
